versions:
  "4":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      PLATFORM_VERSION: "4.0.2"
    test_config:
      cmd:
        - platform --version
        - python --version
        - pip --version
