test_config: &test_config
  cmd:
    - aws --version
    - gitleaks version
    - go version
    - golangci-lint --version
    - migrate -version
    - mockgen -version
    - modd --version
    - rsync --version
    - swagger version

versions:
  "1.21":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
    build_args:
      GITLEAKS_VERSION: 8.18.1
      GOLANGCILINT_VERSION: 1.55.2
      GOMODUPGRADE_VERSION: 0.9.1
      GOSWAGGER_VERSION: 0.30.5
      MIGRATE_VERSION: 4.17.0
      MOCKGEN_VERSION: 1.6.0
      MODD_VERSION: 0.8
  "1.22":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
    build_args:
      GITLEAKS_VERSION: 8.18.1
      GOLANGCILINT_VERSION: 1.55.2
      GOMODUPGRADE_VERSION: 0.9.1
      GOSWAGGER_VERSION: 0.30.5
      MIGRATE_VERSION: 4.17.0
      MOCKGEN_VERSION: 1.6.0
      MODD_VERSION: 0.8
