versions:
  "1":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      GLIBC_VERSION: 2.29-r0
      TRIVY_VERSION: "0.46.0"
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config:
      cmd:
        - aws --version
        - az version
        - docker --version
        - docker-compose --version
        - task --version
        - trivy --version
