versions:
  "1":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      MODD_VERSION: *MODD_VERSION
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config:
      cmd:
        - google-chrome --no-sandbox --version
        - google-chrome-unstable --no-sandbox --version
        - node --version
        - npm --version
        - yarn --version
        - task --version
