test_config: &test_config
  cmd:
    - node --version
    - npm --version
    - aws --version
    - yarn --version
    - sass --version
    - modd --version
    - task --version

versions:
  "18":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      NODE_VERSION: 18.19.0
      NPM_VERSION: 10.2.5
      NVM_VERSION: 0.39.7
      MODD_VERSION: *MODD_VERSION
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config: *test_config
  "20":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      NODE_VERSION: 20.10.0
      NPM_VERSION: 10.2.5
      NVM_VERSION: 0.39.7
      MODD_VERSION: *MODD_VERSION
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config: *test_config
