test_config: &test_config
  cmd:
    - pip --version
    - python --version
    - aws --version

versions:
  "3.8":
    platforms: *base_platforms
    test_config: *test_config
  "3.9":
    platforms: *base_platforms
    test_config: *test_config
  "3.10":
    platforms: *base_platforms
    test_config: *test_config
  "3.11":
    platforms: *base_platforms
    test_config: *test_config
